
#.
#Configs for Modern Train Parts
[server]
	#.
	#The total amount of stacks a container can hold per block in size.
	#Range: > 1
	containerCapacity = 3
	#.
	#The total amount of stacks a bulk storage container can hold per block in size.
	#Range: > 1
	bulkStorageCapacity = 2
	#.
	#The maximal length a wire can go.
	#Range: > 1
	wire_length = 16
	#.
	#The height at which wires should be placed above the train tracks
	#Range: > -2147483648
	wire_track_placement_height = 5

